# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: classical_db
    image: postgres
    restart: always
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_URI: ${DATABASE_URL}
volumes:
  db_data:
